export const MUSEUM_DATA_FETCH_REQUESTED = 'MUSEUM_DATA_FETCH_REQUESTED';
export const MUSEUM_DATA_FETCH_SUCCEEDED = 'MUSEUM_DATA_FETCH_SUCCEEDED';
export const MUSEUM_DATA_FETCH_FAILED = 'MUSEUM_DATA_FETCH_FAILED';
export const CHANGE_BASE_URL = 'CHANGE_BASE_URL';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';

