# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'augus' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for augus
  pod 'AppCenter/Crashes', '~> 1.5.0'
  pod 'AppCenter/Analytics', '~> 1.5.0'
  pod 'AppCenterReactNativeShared', '~> 1.4.0'
  pod 'ViroReact', :path => '../node_modules/react-viro/ios/'
  pod 'ViroKit', :path => '../node_modules/react-viro/ios/dist/ViroRenderer/'

  

  platform :ios, '9.3'
  target 'augusTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# Hack to fix linker error between GVRSDK and React
# see this issue comment https://github.com/facebook/react-native/issues/18022#issuecomment-372760977
post_install do |installer|
  system(". ./pod_post_install.sh")
end