import {
  StyleSheet,
} from 'react-native';

export default StyleSheet.create({
  navigator: {
    flex: 1,
    backgroundColor: 'white',
  },
  screenContainer: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'flex-start',
    backgroundColor: '#f0f0f0',
  },
  body_container: {
    flexGrow: 80,
  },
  listMargin: {
    marginTop: 5,
    marginBottom: 0,
  },
  container: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  rightContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    // backgroundColor: '#333333',
  },
  listCategoryContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#e1057d',
    marginBottom: 16,
    marginRight: 8,
    marginLeft: 8,
    padding: 4,
  },
  listContainer: {
    backgroundColor: '#007da0',
    marginBottom: 16,
    marginRight: 8,
    marginLeft: 8,
    padding: 8,
    height: 100,
    borderRadius: 5,
  },
  listText: {
    flex: 1,
    flexDirection: 'row',
    fontSize: 28,
    textAlign: 'left',
    justifyContent: 'center',
    color: '#fff',
  },
  listCategoryText: {
    flex: 1,
    flexDirection: 'row',
    fontSize: 28,
    textAlign: 'center',
    justifyContent: 'center',
    color: '#fff',
  },
  tabIcon: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
  },
  map: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  thumbnail: {
    width: 120,
    height: 81,
  },
  title: {
    fontSize: 20,
    marginBottom: 8,
    textAlign: 'center',
  },
  year: {
    textAlign: 'center',
  },
  section_name: {
    fontSize: 20,
    marginBottom: 4,
    textAlign: 'center',
  },
  section_name_container: {
    backgroundColor:"#e1057d",
    marginBottom: 4,
  },
  navbar_container: {
    flexGrow: 1,
  },
  stationTitlePane: {
    justifyContent: 'space-between',
    flexGrow: 1,
    flexDirection: 'row',
    marginBottom: 5,
  },
  station_name: {
    fontSize: 32,
    margin: 0,
    marginTop: 10,
    marginBottom: 14,
    textAlign: 'center',
    fontWeight: '500',
    flexWrap: 'wrap',
    flex: 1,
  },
  backButton: {
    fontSize: 32,
    margin: 10,
    marginRight: 20,
    marginLeft: 20,
    textAlign: 'center',
    fontWeight: '500',
    color: 'white',
  },
  station_text: {
    fontSize: 22,
    color: '#000',
    marginTop: 0,
    marginBottom: 14,
  },
  listView: {
    paddingTop: 64,
    backgroundColor: '#F5FCFF',
  },
  contentContainer: {
    padding: 10,
    paddingTop: 5,
    //paddingBottom: 50,
  },
  rightPane: {
    justifyContent: 'space-between',
    flex: 1,
  },
  adventureTitle: {
    flex: 1,
    fontSize: 24,
    fontWeight: '500',
  },
  separator: {
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
    height: StyleSheet.hairlineWidth,
    marginVertical: 10,
  },
  imageDescription: {
    fontSize: 22,
    color: '#000',
  },
  expandIconBox: {
    width: 200,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: -70,
    marginBottom:0,
  },
  expandIcon: {
    fontSize: 48,
    color: '#000',
    backgroundColor: '#ffffff',
    borderWidth: 3,
    borderRadius: 5,
    padding: 10,
    paddingBottom: 5,
    paddingRight: 5,
    marginRight: 5,
  },
  collapseIcon: {
    fontSize: 48,
    color: '#000',
    padding: 10,
  },
  detailsImage: {
    width: 200,
    height: 200,
    backgroundColor: '#eaeaea',
  },
  closeButton: {
    color: 'white',
    textAlign: 'center',
    margin: 10,
    // alignSelf: 'center',
    fontSize: 60,
  },
  closeButtonContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 8,
    borderColor: 'white',
    borderRadius: 5,
    margin: 5,
    alignSelf: 'flex-start',
    backgroundColor: '#000',
  },
  exhibitionImage: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'stretch',
    height: 100,
    backgroundColor: '#eaeaea',
    borderWidth: 3,
    borderColor: '#007da0',
    marginRight: -10,
    marginLeft: -10,
    marginTop: -10,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    padding: 8,
  },
  stationSymbol: {
    height: 40,
    width: 40,
    marginRight: 10,

  },
  imageGallery: {
    paddingTop: 10,
    paddingBottom: 10,
    flexDirection: 'row',
    backgroundColor: '#888',
  },
  imageGalleryBox: {
    justifyContent: 'center',
    flexDirection:'column', 
    flex:1, 
    alignItems: 'center', 
    borderColor:'rgba(0, 0, 0, 0.1)', 
    borderWidth:1, 
    padding: 10, 
    marginRight:5, 
    marginLeft:5, 
    backgroundColor: '#eee',
    borderRadius: 10,
  },
  imageCaption: { 
    flexGrow: 1,
    borderWidth: 10,
  },
  backgroundVideo: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },
  colStretch: {
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  video: {
    height: 210,
    alignSelf: 'stretch',
  },
  lightBox: {
    flex: 1,
    height: 150,
  },
});
